import Head from 'next/head'
import { Inter } from 'next/font/google'
import { trpc } from '@/hooks/trpc'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const result = trpc.hello.useQuery({text: "Daniel"});
  
  if (!result.data){
    return <div>Loading...</div>
  }

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="border border-red-500 p-5">
          { JSON.stringify(result.data) }
        </div>
      </main>
    </>
  )
}
